# This workflow will publish the gwt-visualization-pre-maven.jar to GitHub packages

name: Publish gwt-jakarta-custom to Github Packages

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MAVEN_PACKAGES_TOKEN }}
      GITHUB_ACTOR: NudgeBuild  
      GITHUB_PACKAGE_REPO: https://maven.pkg.github.com/atakama/nudge-legacy-dependencies
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
    
    - name: Publish to GitHub Packages Apache Maven
      run: |
        mvn deploy:deploy-file \
        -DgroupId=org.gwtproject \
        -DartifactId=gwt-codeserver \
        -Dversion=2.11.0-jakarta-SNAPSHOT \
        -Dpackaging=jar \
        -Dfile=lib/org/gwtproject/gwt-codeserver/2.11.0-jakarta-SNAPSHOT/gwt-codeserver-2.11.0-jakarta-SNAPSHOT.jar \
        -DrepositoryId=github \
        -Durl=${{ env.GITHUB_PACKAGE_REPO }} \
        -DpomFile=lib/org/gwtproject/gwt-codeserver/2.11.0-jakarta-SNAPSHOT/gwt-codeserver-2.11.0-jakarta-SNAPSHOT.pom
        mvn deploy:deploy-file \
        -DgroupId=org.gwtproject \
        -DartifactId=gwt-dev \
        -Dversion=2.11.0-jakarta-SNAPSHOT \
        -Dpackaging=jar \
        -Dfile=lib/org/gwtproject/gwt-dev/2.11.0-jakarta-SNAPSHOT/gwt-dev-2.11.0-jakarta-SNAPSHOT.jar \
        -DrepositoryId=github \
        -Durl=${{ env.GITHUB_PACKAGE_REPO }} \
        -DpomFile=lib/org/gwtproject/gwt-dev/2.11.0-jakarta-SNAPSHOT/gwt-dev-2.11.0-jakarta-SNAPSHOT.pom
        mvn deploy:deploy-file \
        -DgroupId=org.gwtproject \
        -DartifactId=gwt-servlet-jakarta \
        -Dversion=2.11.0-jakarta-SNAPSHOT \
        -Dpackaging=jar \
        -Dfile=lib/org/gwtproject/gwt-servlet-jakarta/2.11.0-jakarta-SNAPSHOT/gwt-servlet-jakarta-2.11.0-jakarta-SNAPSHOT.jar \
        -DrepositoryId=github \
        -Durl=${{ env.GITHUB_PACKAGE_REPO }} \
        -DpomFile=lib/org/gwtproject/gwt-servlet-jakarta/2.11.0-jakarta-SNAPSHOT/gwt-servlet-jakarta-2.11.0-jakarta-SNAPSHOT.pom
        mvn deploy:deploy-file \
        -DgroupId=org.gwtproject \
        -DartifactId=gwt-user \
        -Dversion=2.11.0-jakarta-SNAPSHOT \
        -Dpackaging=jar \
        -Dfile=lib/org/gwtproject/gwt-user/2.11.0-jakarta-SNAPSHOT/gwt-user-2.11.0-jakarta-SNAPSHOT.jar \
        -DrepositoryId=github \
        -Durl=${{ env.GITHUB_PACKAGE_REPO }} \
        -DpomFile=lib/org/gwtproject/gwt-user/2.11.0-jakarta-SNAPSHOT/gwt-user-2.11.0-jakarta-SNAPSHOT.pom
        mvn deploy:deploy-file \
        -DgroupId=org.gwtproject \
        -DartifactId=gwt \
        -Dversion=2.11.0-jakarta-SNAPSHOT \
        -Dpackaging=pom \
        -Dfile=lib/org/gwtproject/gwt/2.11.0-jakarta-SNAPSHOT/gwt-2.11.0-jakarta-SNAPSHOT.pom \
        -DrepositoryId=github \
        -Durl=${{ env.GITHUB_PACKAGE_REPO }}
        mvn deploy:deploy-file \
        -DgroupId=org.gwtproject.web.bindery \
        -DartifactId=requestfactory \
        -Dversion=2.11.0-jakarta-SNAPSHOT \
        -Dpackaging=pom \
        -Dfile=lib/org/gwtproject/web/bindery/requestfactory/2.11.0-jakarta-SNAPSHOT/requestfactory-2.11.0-jakarta-SNAPSHOT.pom \
        -DrepositoryId=github \
        -Durl=${{ env.GITHUB_PACKAGE_REPO }}
